export {
  workspaceConfigVersion,
  type AgentView,
  type MessageView,
  type RoomSnapshot,
  type TaskView,
  type WorkspaceAdapterKind,
  type WorkspaceAgentConfig,
  type WorkspaceConfig,
  type WorkspaceConfigPreview,
  type WorkspaceConfigSource,
  type WorkspaceConfigWriteResult,
  type WorkspacePermissionPolicy,
} from "@ai-mesh/application";
export type { TraceRecord } from "@ai-mesh/protocol";

export {
  createBuiltinWorkspaceAdapterRegistry,
  WorkspaceAdapterRegistry,
  type WorkspaceAdapterProvider,
} from "./adapters.js";
export {
  defaultWorkspaceConfig,
  parseWorkspaceConfig,
  previewWorkspaceConfig,
  saveWorkspaceConfig,
  serializeWorkspaceConfig,
  validateWorkspaceConfig,
  WorkspaceConfigConflictError,
  WorkspaceConfigLockedError,
  type SaveWorkspaceConfigInput,
  type WorkspaceConfigInput,
} from "./config.js";
export {
  createWorkspaceSessionId,
  inspectWorkspaceStorage,
  listWorkspaceRegistrations,
  listWorkspaceSessions,
  prepareWorkspaceStorage,
  recordWorkspaceSessionProjection,
  registerWorkspace,
  resolveMeshHome,
  resolveWorkspaceRoot,
  workspaceRegistryVersion,
  workspaceSessionHeaderVersion,
  workspaceSessionProjectionCacheVersion,
  WorkspaceMigrationConflictError,
  WorkspaceMigrationLockedError,
  WorkspaceRegistrationConflictError,
  WorkspaceRegistryLockedError,
  WorkspaceStorageOverlapError,
  WorkspaceSessionCorruptError,
  type WorkspaceRegistration,
  type WorkspaceSessionHeader,
  type WorkspaceSessionProjection,
  type WorkspaceSessionStatus,
  type WorkspaceSessionSummary,
  type WorkspaceStorageInput,
  type WorkspaceStorageLocation,
  workspaceProjectKey,
} from "./storage.js";
export {
  MeshWorkspace,
  type AgentProbeResult,
  type OpenWorkspaceOptions,
  type StartAvailableAgentsResult,
} from "./workspace.js";
